chapters/fundamental_algorithms/tree_traversal.md
Adds Python example to tree traversal code.
=> Python for Tree Traversal

chapters/computational_physics/verlet.md, chapters/fundamental_algorithms/tree_traversal.md
Added C to tree traversal and verlet. I copied the c++ for the verlet and changed the cout to printf and the header.
=> Adding C to the tree traversal and verlet

chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md
=> Adding javascript and c to euclidean algorithm

chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md
also remove unnecessary include of math.h for C and C++
=> add rust, haskell euclidean

chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md
This pull request does the same as #14 but with Java and Python. Both code examples now support negative numbers as input parameters.
=> Negative number support for the Java and Python examples for Euclid's Algorithm

CONTRIBUTORS.md, chapters/mathematical_background/convolutions/code/haskell/convolution.hs, chapters/mathematical_background/convolutions/convolutions.md
I did not add FFT code as it is messy in Haskell AFAIK.
Added my name to contributors :p
=> Added Haskell code for convolutions 

chapters/computational_mathematics/decision_problems/stable_marriage/code/python/stable_marriage.py
When merged, this Pull Request fixes a typo in the Python 3 implementation of the stable marriages problem. Thanks to @Gathros for spotting this one.
=> Fixed a typo in the stable_marriages.py

.gitignore
The updated `.gitignore` catches the files created by various operating systems.
Should we include common editors like `VSCode`, `Vim` and so on in the `.gitignore` as well?
=> Add new .gitignore created with gitignore.io (arguments: Linux, macOS, Windows, GitBook).

.clang-format, chapters/computational_mathematics/FFT/code/c++/fft.cpp, chapters/computational_mathematics/decision_problems/stable_marriage/code/c++/stable_marriage.cpp, chapters/computational_physics/euler/code/c++/euler.cpp, chapters/computational_physics/verlet/code/c++/verlet.cpp, chapters/fundamental_algorithms/euclidean_algorithm/code/c++/euclidean_example.cpp, chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md, chapters/fundamental_algorithms/tree_traversal/code/c++/Tree.cpp, chapters/fundamental_algorithms/tree_traversal/code/c++/Tree_example.cpp, chapters/fundamental_algorithms/tree_traversal/tree_traversal.md, chapters/mathematical_background/convolutions/code/c++/convolutions.cpp
I can add a .clang-format as well;
```
BasedOnStyle: LLVM
AlignAfterOpenBracket: AlwaysBreak
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
PointerAlignment: Left
```
=> switch over to clang-format style

.editorconfig
When merged, this pull request will add a configuration file for EditorConfig. EditorConfig is a collection of plugins that use the same configuration file. Plugins are available for many common text editors. [Go to editorconfig.org for more information and plugin downloads.](http://editorconfig.org/)
The goal of adding such a configuration to the AAA is to make it easier for contributors to write consistently styled code throughout the entire project. The file will mainly contain two options for each language: "indent_style" and "indent_size" for spaces or "tab_width" for tabs.
This Pull Request exists as a place for discussion until we can agree on indentation styles for every language. Feel free to propose more languages that are not currently used in the AAA but could be in the …
=> Create a .editorconfig file

chapters/data_compression/huffman/code/haskell/huffman.hs, chapters/data_compression/huffman/huffman.md
Added Haskell implementation, and fixed a few typos and trailing spaces in huffman.md.
The main issue with the code is that (to simplify implementation) the tree generated can have some branches inverted compared with the algorithm from the video. The bit length doesn't change at all, so it's not a huge deal, maybe.
Thoughts?
=> Added Huffman with Haskell

chapters/data_compression/huffman/code/c++/huffman.cpp, chapters/data_compression/huffman/huffman.md
It doesn't do any encoding/decoding yet; just thought I'd open a PR so that people could comment on it. There's a lot of work here!
EDIT: I'm now finished, and it works, afaict. If people would like to test it, that'd be great; comments are welcome!
=> huffman implementation in C++

chapters/data_compression/huffman/code/c++/huffman.cpp, chapters/data_compression/huffman/huffman.md
change `class` -> `typename` in template parameter lists; this brings the file in line with other C++ files in the project.
change `lang:"cpp"` -> `lang:"c_cpp"`, as the code highlighter uses `"c_cpp"` for highlighting both kinds of files.
=> fix the style and highlighting of huffman.cpp

chapters/sorting_searching/bogo/bogo_sort.md, chapters/sorting_searching/bogo/code/haskell/bogoSort.hs
Added bogo sort, cleaned out trailing spaces too.
I left the implementation for shuffling because it's not part of core libraries in Haskell.
=> Bogo Sort in Haskell

chapters/differential_equations/euler/euler.md
This pull request fixes two "unknown language" errors that appear during the gitbook build process. These are the two that @leios did *not* find during yesterday's livestream.
Note to @leios: Learn grep =P
=> Fixed wrong lang attributes of some code includes

chapters/data_compression/huffman/huffman.md
This PR adds an import statement for the code submitted in #98 to the corresponding markdown file.
=> Add import for the Python Huffman implementation to the chapter

styles/website.css
When I brought up the AAA a few days ago, a friend of mine brought up that he doesn't like how the chapter text ends at the very bottom of the page. [The Introduction chapter is a good example](https://algorithm-archivists.github.io/chapters/introduction.html) - the last line of text is at the very bottom of the monitor when viewing the page in fullscreen. I see where he's coming from, so I tried adding a margin at the bottom and I think it's nicer this way. What do you all think?
=> Add a margin at the bottom of every page

chapters/FFT/code/julia/fft.jl, chapters/computational_geometry/gift_wrapping/graham_scan/code/julia/graham.jl, chapters/matrix_methods/thomas/thomas.md
Here are a few quick updates to the implementation of graham scan. I also slightly modified the spacing in the fft algorithm and removed a comment that shouldn'e be there and fixed some stuff with the `thomas.md` file.
As a note: we indicated that the readme could use some work and should be split so it's not on algorithm-archive.org anymore. The reason we have the readme as the first page is in part because of how gitbook worked when we were using it. Since we are no longer on gitbook, this shouldn't be an issue anymore.
=> adding smallscale changes to graham implementation, fft, and thomas.

chapters/tree_traversal/code/haskell/TreeTraversal.hs, chapters/tree_traversal/tree_traversal.md
- tree traversal in Haskell, it had submitted it before but it got lost
- added post-order
- added in-order, although I'm not super happy with this since it could cause an error. See the issue that I opened about this (how do you link those things?)
- added code snippets into tree_traversal.md, fixed a typo and trailing whitespaces. 
- I have not implemented the stack method, it's basically impossible to avoid recursion in Haskell anyway
=> Re-added tree traversal in Haskell, pre/post/in-order

chapters/monte_carlo/code/d/monte_carlo.d, chapters/monte_carlo/monte_carlo.md
Its a fairly straight forward implementation. Simply run with `rdmd monte_carlo.d`
=> Add D implementation of monte carlo

CONTRIBUTORS.md, chapters/euclidean_algorithm/code/go/euclidean.go, chapters/euclidean_algorithm/euclidean.md
Run with `go run euclidean.go`
=> Add euclidean algorithm implementation for Go

book.json, chapters/sorting_searching/bogo/bogo_sort.md, chapters/sorting_searching/bogo/code/matlab/bogosort.m, chapters/sorting_searching/bubble/bubble_sort.md, chapters/sorting_searching/bubble/code/matlab/bubblesort.m
Inspired by #158, I decided to increase coverage for matlab
=> Added Matlab bubblesort

book.json
The lack of the comma caused the book to not build anymore.
=> Add missing comma.

chapters/euclidean_algorithm/code/python/euclidean_example.py, chapters/euclidean_algorithm/euclidean.md
This is a very minor change, but it is a little more pythonic
=> Removed unnessesary temp variable

CONTRIBUTORS.md, chapters/sorting_searching/bogo/bogo_sort.md, chapters/sorting_searching/bogo/code/python/bogo.py
I am curious to hear your thoughts on python 2 vs python 3, as discussed in #141
=> Added python Bogo Sort

chapters/monte_carlo/code/julia/monte_carlo.jl, chapters/monte_carlo/monte_carlo.md
Hey guys, a lot of people were mentioning that the julia code for monte carlo was unclear. After looking at it again, I agree. I really wanted to have some parameter `radius` in the function, just because I wanted to make it clear that the circle could be an arbitrary size. That said, @jiegillet brought it to my attention, that we clearly say we are using a unit circle in the code, and if we read in a radius of greater than the box length, the code is wrong.
For this purpose, I removed the `radius` parameter from the julia code (except in the `in_circle()` function, but I can remove it there too). I was just being overly cautious to try to make the text easier to read and understand and in the process actually made it more difficult for new contributors.
Let me know what you think. I …
=> simplifying julia code for monte carlo

chapters/sorting_searching/bubble/bubble_sort.md, chapters/sorting_searching/bubble/code/swift/bubblesort.swift
=> Adding Bubble Sort in Swift

chapters/FFT/cooley_tukey.md, chapters/sorting_searching/bogo/bogo_sort.md, chapters/sorting_searching/bubble/bubble_sort.md, chapters/tree_traversal/code/python/Tree_example.py, chapters/tree_traversal/tree_traversal.md
Fixed some off-by-one errors in the markdown code imports.
Completed the tree traversal python implementation.
=> Tidy up code imports

chapters/sorting_searching/bogo/bogo_sort.md
Bogosort's best case runtime is not constant, because even if the array
is already sorted, it still has to perform Θ(n) operations to verify
that each of the n elements are in order.
=> Correct bogosort's best case runtime

.editorconfig
=> Added EditorConfig rule for Matlab and Racket source files

chapters/monte_carlo/code/swift/monte_carlo.swift, chapters/monte_carlo/monte_carlo.md
Added Monte Carlo in Swift 4.1
=> Added Monte Carlo in Swift 4.1

CONTRIBUTORS.md, chapters/euclidean_algorithm/code/haskell/euclidean_example.hs, chapters/euclidean_algorithm/euclidean.md
Avoided hiding values inside "where" bindings.
=> Modified euclidian algorithm haskell code to be more clear and readable

chapters/monte_carlo/code/java/MonteCarlo.java, chapters/monte_carlo/monte_carlo.md
Changed the monteCarlo function to return a double so print statements are done in main()
I think the code is a bit cleaner this way but it may just be a personal preference so I understand if this isn't merged
=> Small Change to Java implementation of Monte Carlo

chapters/tree_traversal/code/cs/Program.cs, chapters/tree_traversal/code/cs/Tree.cs, chapters/tree_traversal/tree_traversal.md
Restructure code by removing the `Node` class. Remove `CreateAllChildren` method and make the constructor do it instead.
This is applying the changes suggested @Gustorn in https://github.com/algorithm-archivists/algorithm-archive/pull/137 in discussion with @xam4lor .
The PR also removes the `CreateAllChildren` method and just makes the constructor recursive and do the creation.
=> Update Tree Traversal C#.

chapters/euclidean_algorithm/code/python/euclidean_example.py
made it use a one print instead of two and deleted the function that was handling the two prints and made it print directly and used a -= b, b -= a instead of a = a - b, b= b - a
=> Cleaned up the code a bit

chapters/matrix_methods/gaussian_elimination/gaussian_elimination.md, chapters/tree_traversal/tree_traversal.md
- Changing tree_traversal.md to show rust code
- Putting ###Haskell in correct place (currently 'Haskell' shows up after the Rust code in Gaussian Elimination)
=> Small fix to two .md files

chapters/sorting_searching/bogo/code/swift/bogosort.swift, chapters/sorting_searching/bubble/bubble_sort.md
My current understanding is that code in the AAA is supposed to have a main() function to run the algorithm. So I updated the swift sorting algorithms to reflect this.
- Changed bubble_sort.md so main() is now shown
- Added main() to bogo sort
=> Adding main() to Swift sorting algorithms

chapters/computational_geometry/gift_wrapping/graham_scan/graham_scan.md, chapters/computational_geometry/gift_wrapping/jarvis_march/jarvis_march.md, chapters/data_compression/huffman/huffman.md, chapters/decision_problems/stable_marriage/stable_marriage.md, chapters/differential_equations/euler/euler.md, chapters/euclidean_algorithm/euclidean.md, chapters/matrix_methods/gaussian_elimination/gaussian_elimination.md, chapters/matrix_methods/thomas/thomas.md, chapters/monte_carlo/monte_carlo.md, chapters/physics_solvers/quantum/split-op/split-op.md, chapters/physics_solvers/verlet/verlet.md, chapters/tree_traversal/tree_traversal.md
- Made 'Example Code' a consistent size throughout document
- Added in 'Example Code' on several pages
- Added in missing programming language titles
=> Fixing 'Example Code'

chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md, chapters/algorithms/forward_euler_method/forward_euler_method.md, chapters/algorithms/gaussian_elimination/gaussian_elimination.md, chapters/algorithms/graham_scan/graham_scan.md, chapters/algorithms/huffman_encoding/huffman_encoding.md, chapters/algorithms/jarvis_march/jarvis_march.md, chapters/algorithms/monte_carlo_integration/monte_carlo_integration.md, chapters/algorithms/split-operator_method/split-operator_method.md, chapters/algorithms/stable_marriage_problem/stable_marriage_problem.md, chapters/algorithms/thomas_algorithm/thomas_algorithm.md, chapters/algorithms/tree_traversal/tree_traversal.md, chapters/algorithms/verlet_integration/verlet_integration.md
@Butt4cak3 realized we no longer need the language headlines so this PR removes them. This can be seen in PR #245
=> Removing All Language Headlines

chapters/algorithms/verlet_integration/code/c++/verlet.cpp, chapters/algorithms/verlet_integration/verlet_integration.md
- make functions return time
- assign value to vars at declaration
- use next_pos var name instead of tmp_pos (delete comment)
=> Improve readability of examples in verlet.cpp

chapters/algorithms/euclidean_algorithm/code/java/EuclideanAlgo.java, chapters/algorithms/euclidean_algorithm/code/java/MainClass.java, chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md
I think that the Euclidean Algorithm should be implemented and run within a single class rather than two. So I modified the implementation of the Euclidean Algorithm in Java to only be one class. I made the following changes:
- Removed MainClass.java file
- Added main() function to EuclideanAlgo class
- Modified euclidean.md to reflect changes
This may just be a personal preference though so I understand if it isn't merged 👍
=> Changes to Euclidean Algorithm in Java

chapters/algorithms/gaussian_elimination/code/julia/gaussian_elimination.jl, chapters/algorithms/gaussian_elimination/gaussian_elimination.md
- rename gauss_jordan function to gauss_jordan_elimination
- do gauss_jordan_elimination in-place, to match with gaussian_elimination
=> Improve consistency of Julia code for Gaussian elimination

README.md
We're receiving an increasing number of PRs of people trying to submit entirely new chapters. Even though @leios decided that he would allow some people to write new chapters, it's not an entirely open-to-the-public process yet.
This PR adds a very visible note right at the top of the README.md file in the root of this repository. I think a note like this is long overdue. New contributors cannot know the current situation when it comes to chapter contributions. With this note, we can at least point to something when we close such PRs.
=> Added a note in README.md for new contributors

contents/euclidean_algorithm/euclidean_algorithm.md, contents/huffman_encoding/huffman_encoding.md
Found some attempted code cutoffs in the 'Example Code' section of two .md files. Although I don't think they actually do anything due to missing colons. 
- Removed attempted code cutoffs
=> Small .md Fixes for 'Example Code'

contents/forward_euler_method/code/swift/euler.swift, contents/forward_euler_method/forward_euler_method.md
=> Adding Forward Euler in Swift

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/java/bogo.java, contents/bogo_sort/code/javascript/bogo.js, contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/java/bubble.java
My current understanding is that code in the AAA is supposed to show a main() function which runs the algorithm. So I updated the java sorting algorithms to reflect this.
- Changed bubble_sort.md so main() is now shown
- Changed bogo_sort.md so main() is now shown
=> Adding Example Code to Sorting Algorithms

contents/verlet_integration/code/python/verlet.py, contents/verlet_integration/verlet_integration.md
During a recent discussion about #243 I noticed that the Python version of our Verlet Integration example code is vastly different from all other implementations. It creates a `Simulation` class and the 3 Verlet algorithms are classes that inherit from that `Simulation` class.
I changed the code to more closely match the other language implementations because I think that introducing classes and inheritance to a piece of example code like this is a bit excessive. Tell me what you think.
=> Reimplemented Verlet Integration in Python

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/swift/bogosort.swift, contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/swift/bubblesort.swift, contents/forward_euler_method/code/swift/euler.swift, contents/monte_carlo_integration/code/swift/monte_carlo.swift, contents/monte_carlo_integration/monte_carlo_integration.md
Small changes to some swift code. Just adjusted whitespace to make formatting more consistent across swift code and I think it looks a bit cleaner. Doesn't really matter but it bothered me a bit
=> Adjusting Whitespace in Swift Code

contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/c++/bubblesort.cpp
- remove random generator function
- use nested loop instead of is_sorted var
=> Cleanup bubble sort code for C++

contents/verlet_integration/code/c/verlet.c, contents/verlet_integration/verlet_integration.md
Done according to https://github.com/algorithm-archivists/algorithm-archive/issues/257.
=> Update C implementations for Verlet algorithms

contents/euclidean_algorithm/code/swift/euclidean_algorithm.swift, contents/euclidean_algorithm/euclidean_algorithm.md
In Swift parameters are immutable. The way this is typically dealt with is to create a local mutable version of the parameter with the same name. I had essentially done this but had not used the same name as the parameter. 
So I replaced all 'A'/'B's in the code with 'a'/'b's. This helps the code to both be cleaner and more in line with the typical Swift style.
I also removed some whitespace.
=> Improving Euclidean Algorithm in Swift

book.json, contents/euclidean_algorithm/code/lua/euclidean.lua, contents/euclidean_algorithm/euclidean_algorithm.md
I've been learning a little bit of Lua. So I figured I should add some to the AAA.
=> Adding Euclidean Algorithm in Lua

.travis.yml, tools/deploy/update_site_travis.bash
If you turn on Travis continuous integration (free), you can test code in a remote container and do other neat stuff, like deploy documentation...or a book.
1. "Test" the repository by making sure the book builds. CI runs automatically at every update for every PR, and every merge to master. https://github.com/algorithm-archivists/algorithm-archive/pull/281 would have been caught before merging.
2. If the book builds successfully, and this is a merge to master, push the book to a remote repo. No more need to update manually.
1 can exist without 2, so if you don't like it, that part can be removed. The results for my build are at https://travis-ci.com/berquist/algorithm-archive. Signing up for Travis CI is relatively easy, but if you want point 2, here is the extra work required. …
=> Automatically build book and deploy to a repo

CONTRIBUTORS.md, book.json, contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/crystal/bubble.cr
=> Added Bubble Sort in Crystal

contents/monte_carlo_integration/code/csharp/Circle.cs, contents/monte_carlo_integration/code/csharp/MonteCarlo.cs, contents/monte_carlo_integration/code/csharp/Program.cs, contents/monte_carlo_integration/monte_carlo_integration.md
Since [this PR](https://github.com/algorithm-archivists/algorithm-archive/pull/239) is dead, I wrote it myself.
=> Add Monte Carlo Integration in C#

contents/thomas_algorithm/code/haskell/thomas.hs, contents/thomas_algorithm/thomas_algorithm.md
Also corrects minor typo in the chapter.
That's a short one. @lulucca12 I think this one will be more to your liking.
@leios that chapter is a little weak on the explanation of the algorithm. In particular, I don't get "In particular, we need to find an optimal scale factor for each row and use that.". Also you write down the formula for the forward step, but you don't explicit the back substitution (sure, it's similar to the gaussian elimination but the result is so simple...). I know that you have many things to do. Would you be OK with me fleshing it out a bit? (In another PR this time!!)
=> Added Thomas Algorithm in Haskell

contents/forward_euler_method/code/c++/euler.cpp
- use for-loop instead of generate_n and back_inserter and lambda
- use C++ style of commenting to follow C++ Coding Standards section Comments
=> Minor clean up for Forward Euler Method in C++

book.json
This is applicable if
I set version which is currently as fallback **2.6.1** but it's possible use any version, just changing **book.json** for future :)
=> Added mathjax reference on algorithm-archivists/plugin-mathjax

contents/tree_traversal/code/rust/tree.rs, contents/tree_traversal/tree_traversal.md
Figured I could quickly add in the dfs_recursive_postorder function in Rust since it is so similar to the dfs_recursive.
The inorder binary tree function is still missing.
=> Adding the Missing Rust Tree Traversal Functions

contents/tree_traversal/code/python/Tree_example.py
- Corrected recursion in DFS_recursive_postorder
- Fixed DFS_recursive_inorder_btree
- Called DFS_recursive_postorder and DFS_recursive_inorder_btree in main()
=> Small Corrections for Tree Traversal in Python

contents/tree_traversal/code/rust/tree.rs
Creating trees is also more consistent with the Julia implementation.
=> Fix typo in Rust tree traversal

contents/thomas_algorithm/thomas_algorithm.md
Let me know what you think, maybe I went into too much detail?
=> Re-wrote Thomas Algorithm chapter to include more details

contents/tree_traversal/code/swift/tree.swift, contents/tree_traversal/tree_traversal.md
=> Adding Tree Traversal in Swift

CONTRIBUTORS.md, contents/monte_carlo_integration/code/c++/monte_carlo.cpp, contents/monte_carlo_integration/monte_carlo_integration.md
I just came across this project and wanted to chip in something. Hope this conforms to any style preferences. 👍
=> Implement C++ version of Monte Carlo integration

book.json, contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/nim/bogo_sort.nim
I implemented bogo sort in nim, I also fixed a small formatting error I made in my last commit under book.json (the nim lang section was off a space).
=> implemented bogo sort in nim

contents/monte_carlo_integration/code/nim/monte_carlo.nim, contents/monte_carlo_integration/monte_carlo_integration.md
monte carlo integration in nim.
=> implemented monte carlo integration in nim

contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/nim/bubble_sort.nim
Implemented the bubble sort algorithm in nim.
=> implemented bubble sort in nim

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/javascript/bogo.js
Added main() to code so that it can be run as is
=> Implementation Edit to Bogo Sort in Javascript

contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/javascript/bubble.js
Added main() to code so that it can be run as is
=>  Implementation Edit to Bubble Sort in Javascript

contents/cooley_tukey/code/c++/fft.cpp, contents/cooley_tukey/cooley_tukey.md
- rename c64 to complex
- make pi a constant instead of function
- fix complilation warnings about comparing signed int with unsigned int
=> Minor clean up for cooley tukey in C++

contents/verlet_integration/code/swift/verlet.swift, contents/verlet_integration/verlet_integration.md
Added Verlet Integration in Swift
=> Adding Verlet Integration in Swift

contents/verlet_integration/code/julia/verlet.jl, contents/verlet_integration/code/rust/verlet.rs, contents/verlet_integration/verlet_integration.md
This makes the changes outlined in https://github.com/algorithm-archivists/algorithm-archive/issues/257.
This is also the first Rust code I've ever written, so I don't know if it's idiomatic other than the implicit return. See [here](https://stackoverflow.com/a/51278038/3249688) for the approach.
=> Update Rust implementations for Verlet algorithms

contents/verlet_integration/code/c++/verlet.cpp, contents/verlet_integration/verlet_integration.md
Done according to https://github.com/algorithm-archivists/algorithm-archive/issues/257.
=> Update C++ implementations for Verlet algorithms

contents/monte_carlo_integration/code/rust/monte_carlo.rs
=> Fixing percent error in monte_carlo.rs

contents/monte_carlo_integration/code/swift/monte_carlo.swift, contents/monte_carlo_integration/monte_carlo_integration.md
XCode 10 was recently released and came out with Swift 4.2. So here is an updated version of Monte Carlo Integration in Swift. I was able to get rid of the extension to create random numbers and used Swift's new built in functionality to do this.
=> Updating Monte Carlo in Swift 4.1 to Swift 4.2

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/swift/bogosort.swift
XCode 10 was recently released and came out with Swift 4.2. So here is an updated version of Bogo Sort in Swift. I was able to get rid of the shuffle function I wrote and use Swift's new built in Shuffle function.
=> Updating Bogo Sort in Swift 4.1 to Swift 4.2

contents/gaussian_elimination/code/python/gaussian_elimination.py, contents/gaussian_elimination/gaussian_elimination.md
Python implementation using numpy
=> Implement gaussian elimination in python

.travis.yml, tools/deploy/update_site_travis.bash
Continuation of https://github.com/algorithm-archivists/algorithm-archive/pull/284.
Don't merge this yet, because things need to be added.
The last PR failed in three ways:
1. The site went down because the CNAME for custom domain redirection was not present. After checking the log ([which I saved](https://github.com/algorithm-archivists/algorithm-archive/files/2239118/409399060.txt)), if you're curious, I noticed that there are several other files present in algorithm-archivists.github.io that do _not_ come from either the main repo or building the book. These can persist because `update_site.sh` only copies files over, rather than wipe and move. This is personal preference, but I think the website repo should be entirely reproducible from the main repo via this script. You can see the …
=> Use Travis CI to test the book build and then deploy it to the site, take 2

.travis.yml
https://docs.travis-ci.com/user/customizing-the-build/#customizing-the-build-step
Placing the deployment in `after_success` works around the fact that all
commands under `script` run even when one or more of them return a non-zero
exit code.
=> Prevent Travis from deploying the book, even when it fails.

contents/split-operator_method/split-operator_method.md
This pull request is one of the two new pull requests requested in #409 and is made to fix the line numbers in the C lang implementation in the split operator method.
=> Fixed line numbers for C lang for the split operator markdown

contents/tree_traversal/code/haskell/TreeTraversal.hs, contents/tree_traversal/tree_traversal.md
Added DFS Stack.
I also ran hindent which reformatted the file, so I had to change all import lines.
For the record, it's not _really_ using stacks, just as BFS is not _really_ using queues and the other DFS  implementations are definitely better. I'm just adding it for completeness.
=> Haskell: added DFS Stack to Tree Traversal

contents/verlet_integration/code/haskell/verlet.hs, contents/verlet_integration/verlet_integration.md
Added all methods to Verlet algorithms.
Yay #hipsterhacktoberfest #394 
@leios I think your Julia code for calculating the velocity in Stormer Verlet is not correct. You use `v += a * dt` instead of `v = (pos - prev_pos) / dt`, which actually yields better results but it's not the method you explain in the text.
=> Haskell: added Stormer Verlet and Velocity Verlet

contents/convolutions/code/haskell/convolution.hs, contents/convolutions/convolutions.md
=> Haskell:  added FFT method for convolution

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/ruby/bogo.rb
...mostly by taking full advantage of builtins
I'm not quite sure how implementation edits work -- there are a few Ruby implementations I want to make more idiomatic; should I put them all in one PR or do one PR per algorithm?
=> Making the Ruby bogosort more idiomatic

.editorconfig
This is best to merge before other PHP PRs, so I can update code with this code style
=> Added EditorConfig for PHP from Symfony coding standard

contents/monte_carlo_integration/code/c/monte_carlo.c
MonteCarlo in C was not implemented as described by the book. In the book we are told to use only the first quadrant to calculate pi. The C code produces a random range from -1 to +1. While the method stills works I think we should keep code to follow the algorithm as described by the book.
I also removed the incorrect formula where radius != 0.0 and replaced it with code to product random variables from 0 to radius.
Another smaller change was changing the return type to double. The function should only calculate pi and return it, there's no need for it to also print the estimation and how close it was, that can be left up to the main function.
=> Monte carlo C fix

contents/euclidean_algorithm/code/ruby/euclidean.rb, contents/euclidean_algorithm/euclidean_algorithm.md
Noticed a little hole in our ~~defenses~~ coverage, and I like Ruby, so have another non-Factor PR.
=> Add Euclidean algorithm in Ruby

contents/bubble_sort/code/nim/bubble_sort.nim
It was recently brought to my attention that my nim code has some style mistakes. I have changed the indentation and formatting in this program in accordance to the official nim style guide.
=> fixed formatting in nim bubblesort

contents/euclidean_algorithm/code/nim/euclid_algorithm.nim
Just going through and fixing the formatting errors in the nim programs. I change the indentation and change temp from a var to a let, since the it didn't need to mutable
=> change formatting in euclid alg in nim

contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/javascript/bubble.js, contents/euclidean_algorithm/code/javascript/euclidean_example.js, contents/verlet_integration/code/javascript/verlet.js, contents/verlet_integration/verlet_integration.md
Some of the JavaScript examples were incorrectly formatted (i. e. indentation) and used generally outdated code styles (`var`, etc.). I reformatted them and changed them to use more modern JavaScript concepts.
=> Improved some JavaScript examples

contents/stable_marriage_problem/code/php/stable_marriage.php, contents/stable_marriage_problem/stable_marriage_problem.md
Worked as intended on provided sample 💃
=> Implementation Stable marriage problem in PHP

contents/monte_carlo_integration/code/nim/monte_carlo.nim
I changed the indentation so that it is in accordance with the style guide and I change the types of pi_estimate, x, and y from vars to lets since they did not need to be mutable.
=> fixed formatting issues in nim implementation of monte carlo

contents/jarvis_march/code/golang/jarvis.go, contents/jarvis_march/jarvis_march.md
compiled with `go version go1.11 linux/amd64` and without errors
=> add the jarvis march in go

contents/verlet_integration/code/golang/verlet.go, contents/verlet_integration/verlet_integration.md
run with `go version go1.11 linux/amd64`
=> Add verlet integration in golang

contents/thomas_algorithm/code/julia/thomas.jl
Yeah. That last version of Julia was complete and utter garbage. This fixes that and is modelled after the C code.
=> Fixing Julia for Thomas algorithm

contents/thomas_algorithm/code/java/Thomas.java, contents/thomas_algorithm/thomas_algorithm.md
When merged, this PR fixes a few issues with the Java implementation of the Thomas algorithm and also changes it so that it works similarly to the new Julia implementation (#495).
* The class and file name were `thomas`, but classes in Java should be PascalCase, so I renamed them to `Thomas`.
* The `thomasAlgorithm` method had a `int size` parameter, which is not needed in Java. I assume that the code was directly ported from the C implementation and that was not taken out.
* I had a short talk with @leios on stream today. I mentioned how almost none of the implementations return the result. Instead, they all modify the input vector, which they get passed by reference. The new version of this does not modify any of the input vectors and returns the output vector.
* The output was quite …
=> Clean up Java implementation of Thomas Algorithm

contents/huffman_encoding/code/asm-x64/huffman.s
The current version incorrectly addressed the codebook as `base ptr + index * 20` instead of `base ptr + index * 40`. This resulted in corrupted codebook entries when the message contained characters whose ASCII codes are right next to each other
=> Fix the x64 assembly version of Huffman encoding

book.json
Bash is bash and sh is sh. Those two are different shells. What was used here was bash so i corrected it in the book.json
=> Fix book.json

contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/bash/bubble_sort.bash
More bash algos!
```
(( tmp = arr[(( j + 1 ))] ))
(( arr[(( j + 1 ))] = arr[j] ))
```
these look pretty crippled tho not sure how to make it clearer tbh
=> Added bubblesort in bash

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/lisp/bogo-sort.lisp
In the spirit of bogo sort I've patched this one together rather quickly, the shuffle is slow and the sortedp could maybe be simpler. But it overal works, ship it! :)
=> Lisp bogo sort

.editorconfig
Crystal has its own formatter anyway (`crystal tool format`), but this is still nice to have.
=> Added crystal to .editorconfig

.gitignore
I installed gitbook locally, so npm generated the package-lock.json file. As it is not part of the repo, it should be ignored.
=> Added package-lock.json to .gitignore

contents/bogo_sort/code/julia/bogo.jl, contents/bubble_sort/code/julia/bubble.jl, contents/gaussian_elimination/code/julia/gaussian_elimination.jl, contents/graham_scan/code/julia/graham.jl, contents/huffman_encoding/code/julia/huffman.jl, contents/split-operator_method/code/julia/split_op.jl
By convention, Julia functions that mutate one of their parameters need to have an exclamation mark at the end of their name; this fixes all instances of that that I could find.
=> Added exclamation marks to mutating julia functions

CONTRIBUTORS.md, contents/thomas_algorithm/code/lua/thomas.lua, contents/thomas_algorithm/thomas_algorithm.md
I chose not to mutate the input tables. Is that important?
=> Implemented Thomas Algorithm in Lua

contents/thomas_algorithm/code/julia/thomas.jl
This is the best way to print is nicely, I think.
=> Fixed printing of the Thomas Algorithm implementation in Julia

contents/quantum_systems/code/c++/energy.cpp, contents/quantum_systems/quantum_systems.md
As requested in #420, I've implemented the energy calculations in the quantum system chapter.
=> C++ quantum systems' energy calculations implementation

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/php/bogo_sort.php, contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/php/bubble_sort.php, contents/tree_traversal/code/php/tree_traversal.php, contents/tree_traversal/tree_traversal.md
This PR unifies PHP implementations, which were pushed before defining code style.
Functionality is same, except one less output in TreeTraversal, which was JSON of the tree.
=> PHP unify code style

contents/forward_euler_method/code/java/Euler.java, contents/forward_euler_method/code/java/ForwardEuler.java, contents/forward_euler_method/forward_euler_method.md
Edits are fine, but please provide any feedback you can so I can make my next PRs better
=> Add Java implementation of Forward Euler

contents/cooley_tukey/code/haskell/fft.hs, contents/cooley_tukey/cooley_tukey.md
Added previously missing DFT and re-wrote FFT, I was quite unhappy with it, it's better now.
Yay #hacktoberfest #394!
=> Haskell: added DFT and re-wrote FFT

contents/forward_euler_method/code/nim/forwardeuler.nim, contents/forward_euler_method/forward_euler_method.md
I added a nim implementation of the forward euler method.
=> added a nim implementation of the forward euler method

contents/gaussian_elimination/code/java/GaussianElimination.java, contents/gaussian_elimination/code/julia/gaussian_elimination.jl, contents/gaussian_elimination/code/python/gaussian_elimination.py, contents/gaussian_elimination/code/rust/gaussian_elimination.rs, contents/gaussian_elimination/gaussian_elimination.md
These are revisions to the Gaussian elimination chapter. I will update this some more, but feel free to look at it now and tell me what needs to be updated. I know we are missing references, but I feel this is a step in the right direction.
I will get the Gaussian Elimination video done this weekend, but will only publish the video once the revisions are complete.
=> Gaussian elimination revisions

contents/bitlogic/bitlogic.md, contents/euclidean_algorithm/euclidean_algorithm.md, contents/forward_euler_method/forward_euler_method.md, contents/gaussian_elimination/gaussian_elimination.md, contents/huffman_encoding/huffman_encoding.md, contents/monte_carlo_integration/monte_carlo_integration.md, contents/split-operator_method/split-operator_method.md, contents/stable_marriage_problem/stable_marriage_problem.md, contents/tree_traversal/tree_traversal.md, contents/verlet_integration/verlet_integration.md
This PR adds a video to each chapter with a video associated with it. I understand if people are against this.
=> Adding videos to chapters

contents/gaussian_elimination/gaussian_elimination.md
I changed the format of the GE video to be mp4 so we could play in a number of browsers and put it directly into the md instead of using a youtube link.
=> adding new video to GE chapter.

contents/cooley_tukey/code/c/fft.c, contents/cooley_tukey/cooley_tukey.md
=> C adding FFT test

contents/bogo_sort/code/rust/bogosort.rs, contents/bubble_sort/code/rust/bubble_sort.rs, contents/euclidean_algorithm/code/rust/euclidean_example.rs, contents/monte_carlo_integration/code/rust/monte_carlo.rs, contents/tree_traversal/code/rust/tree.rs, contents/verlet_integration/code/rust/verlet.rs
Simply formats the Rust code using the community standard formatting ([`rustfmt`](https://github.com/rust-lang/rustfmt)).
=> Format Rust code using rustfmt

contents/tree_traversal/code/rust/tree.rs, contents/tree_traversal/tree_traversal.md
Destructuring an array using pattern matching makes the code more readable. This is a more idiomatic solution in Rust. 
This PR also adds a bit of space in the example to make it more readable in accordance with the [code style](https://github.com/algorithm-archivists/algorithm-archive/wiki/Code-style-guide) for the AAA.
=> Use pattern matching in tree traversal (Rust)

README.md
It always bothered me that the links in the second paragraph of the README are quite convoluted, so I went ahead and put them in a list. I also did made a few little other improvements.
- Use a list with short entries for the enumeration of links to other interesting sites/platforms/things in the second paragraph. (Review that influenced this part: https://github.com/algorithm-archivists/algorithm-archive/pull/574#discussion_r246228118)
- Use an absolute link to the How-to-Contribute wiki entry to make the sentence less convoluted. (Review that influenced this part: https://github.com/algorithm-archivists/algorithm-archive/pull/574#discussion_r246227846)
- Fix markdown style issues.
- https://github.com/DavidAnson/markdownlint/blob/v0.11.0/doc/
Rules.md#md012
- …
=> Make README more readable.

contents/bitlogic/bitlogic.md
=> Minor edit to the Bit Logic page

contents/bubble_sort/code/python/bubblesort.py
The current variable name 'number' is a little generic and it doesn't really point to an array.  It may confuse a beginner
=> Variable name change

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHAPTER_REQUEST.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE/CHAPTER_SUBMISSION_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/CODE_SUBMISSION_TEMPLATE.md
I am still working on the chapter submission guidelines, but I figured we could go ahead and put these up for review in the meantime. Don't merge until that section of the wiki is completed!
=> adding some templates to be modified in review

contents/cooley_tukey/code/julia/fft.jl
The julia implementation of fft had an approximate function we created ourselves, but there was no reason to do so when the `isapprox(a,b)` function exists
=> using isapprox(a,b) function in julia instead of rolling our own

contents/euclidean_algorithm/euclidean_algorithm.md, contents/verlet_integration/code/clisp/verlet.lisp, contents/verlet_integration/verlet_integration.md
Not completely happy with this one, it's still a bit of a work in progress.
=> Verlet implementation in Common Lisp

book.json
Kotlin is a JVM-based language from JetBrains. Its name is fully capitalized on the Algorithm Archive website.
This happened because its name is not in the [book.json](https://github.com/algorithm-archivists/algorithm-archive/blob/master/book.json) file.
The pull request adds Kotlin to book.json and fixes the issue.
=> Kotlin capitalization fix

contents/graham_scan/code/c++/graham_scan.cpp, contents/graham_scan/graham_scan.md
Unsure if I should also take this opportunity to C++-ify things (things should be passed by const reference).
=> Apply clang-format to Graham Scan in C++

contents/bogo_sort/code/go/bogo_sort.go, contents/jarvis_march/code/golang/jarvis.go
bogo_sort - there was no need for references everywhere, because a slice is a pointer by nature (values can be changed) and the code doesn't use append or anything else that would change the size, and, possibly, the initial address of the slice
jarvis - the equal function had a typo, perhaps the example should be improved, in the future, to catch this case
=> A couple of GoLang code improvements

README.md
This PR will remove the notice at the start of the Algorithm Archive specifying that we no longer accept new chapters. From here on, we should have no problem merging new chapters because the licensing has been completed and I have time to review again.
Let me know if anyone has any problems with this. This marks a slightly different design methodology for the AAA moving forward where I am not longer the only author.
=> removing notice from README

contents/bubble_sort/bubble_sort.md, contents/euclidean_algorithm/euclidean_algorithm.md, contents/monte_carlo_integration/monte_carlo_integration.md, contents/thomas_algorithm/thomas_algorithm.md, contents/tree_traversal/tree_traversal.md, contents/verlet_integration/verlet_integration.md
PR to "regularize" language markers.
If someone selected a specific language in a specific chapter, for certain languages, the language would not be carried over to certain other chapters, even though an implementation in the same language would exist. Like, if one was looking at the C implementation of Bogo Sort, then he moved on to Euclidean Algorithm. The archive would still show the C implementation here instead of the default. But this doesn't work for certain languages. The problem is regarding the inconsistency in the tags used for the lang markers in the markdown files for each chapter (i.e. the `{% sample lang="<language>" %}` for the sample). So, I changed the language markers for these files so that the language carries over to different files, for the separate markers.
- …
=> Regularize lang markers

.github/FUNDING.yml
I was recently accepted into the github sponsors program and would like to add a funding button here and also potentially on the front page. As this is a somewhat significant change to the AAA, it is worth discussing a bit.
This would involve adding a new chapter for sponsors and such and on the main page as well. I am up for editing the current tiers as well, so let me know if you think of better reward tiers: https://github.com/sponsors/leios
=> adding FUNDING.yml file

contents/computus/computus.md
I changed all the markdown such that year is written in text (not the wiggly LaTeX letters). I also added a bit of hspace between the modulo operator in the chapter because the first one has it but the rest do not.
=> Small changes to computus

contents/computus/code/julia/gauss_easter.jl
Replaced division and flooring with actual floor division. Also prettified formatting and print statements.
=> Improved julia implementation of Computus

contents/computus/code/crystal/gauss_easter.cr, contents/computus/code/julia/gauss_easter.jl, contents/computus/code/python/gauss_easter.py
There is no reason for the return types to be different if you are returning the number needed for Servios' table.
As a note, we probably need a better way of displaying the table at the end because tab spacing is inconsistent on different terminal emulators
=> modifying gauss's easter algorithm to always output strings

contents/cooley_tukey/code/python/fft.py, contents/cooley_tukey/cooley_tukey.md
I used `autopep8` for this. (Now that I think about it, lines 33-34 in the new code seem a little suspect. Let me know if you want me to fix them up a bit.)
=> Make fft.py conform to PEP8

contents/bitlogic/bitlogic.md, contents/bubble_sort/bubble_sort.md, contents/cc/license.txt, contents/computus/computus.md, contents/cooley_tukey/cooley_tukey.md, contents/euclidean_algorithm/euclidean_algorithm.md, contents/gaussian_elimination/gaussian_elimination.md, contents/huffman_encoding/huffman_encoding.md, contents/monte_carlo_integration/monte_carlo_integration.md, contents/notation/notation.md, contents/plotting/plotting.md, contents/quantum_systems/quantum_systems.md, contents/split-operator_method/split-operator_method.md, contents/taylor_series_expansion/taylor_series_expansion.md, contents/thomas_algorithm/thomas_algorithm.md, contents/tree_traversal/tree_traversal.md
Fixing a bunch of minor typos and scaling images.
=> fixing images to scale with available width and a few typos

contents/split-operator_method/code/rust/split_op.rs, contents/split-operator_method/split-operator_method.md
@Gathros and @strega-nil do you want to help make this code more rusty, especially with those very short for-loops. (I essentially translated the preexisting C++ implementation and kept fighting the borrow checker until it worked.)
=> Add Split-Operator in Rust

CONTRIBUTORS.md, contents/IFS/IFS.md, contents/IFS/code/c++/IFS.cpp
My C++ version is slightly different than the Julia version. I decided to exclude saving to a file from the chaosGame() function; I find it cleaner, and cause less distraction when reading the page.
=> Implement IFS in C++

contents/IFS/IFS.md, contents/IFS/code/julia/IFS.jl
This fixes the Julia code to match #700 and #701, and also embeds the lated youtube video
=> fixing Julia code and embedding latest video

contents/monte_carlo_integration/code/julia/monte_carlo.jl
As noted in #696, the Julia implementation needed to be updated to return the pi estimate and not print in the function
=> fixing julia function to output pi estimate

contents/thomas_algorithm/code/rust/thomas.rs, contents/thomas_algorithm/thomas_algorithm.md
For leios: This one is implemented without any external crates, so you can compile it just with `rustc`. (Let me know if what I did for pretty-printing on line 37 of the code was too much.)
=> Add Thomas Algorithm in Rust

contents/euclidean_algorithm/euclidean_algorithm.md, contents/forward_euler_method/code/clisp/euler.lisp, contents/forward_euler_method/forward_euler_method.md
=> Forward euler implementation in Common Lisp

CONTRIBUTORS.md, contents/IFS/IFS.md, contents/IFS/code/python/IFS.py
I tried to adapt the julia code as closely as possible, with just a few python-specific tweaks.
I opted to only use base python packages so that the code would be usable for more people (with numpy, I think this is a one-liner).
Additionally, I intentionally used some python specific syntax and structuring (like "[x for x in y]" list comprehension and the zip function, etc) because I felt it was truer to the language, than doing the usually thing of making a full for loop block that loops over an index. This whole thing would be much cleaner if base python had element-wise addition. . . *sigh*
=> Add IFS in python

book.json, contents/euclidean_algorithm/code/coconut/euclidean.coco, contents/euclidean_algorithm/code/cocount/euclidean.coco, contents/euclidean_algorithm/euclidean_algorithm.md
Here is the euclidean algorithm as one could implement it in the Coconunt programming language.
It uses pattern matching, and Coconut optimizes tail call recursion, so the algorithm will not exceed max recursion depth.
As it's the first time someone seems to have implemented an AAA algorithm in this language, there are a few things you need to know about it.
First (some advertising for Coconut): Coconut is compiled language which is a strict superset of Python 3: all valid Python code is valid Coconut code. The Coconut compiler compiles to Python. Coconut also adds more functional programming features built-in than Python does. You can find their website at: http://coconut-lang.org, and docs at https://coconut.readthedocs.io/en/master/DOCS.html
Second: Installation instructions: `pip …
=> Euclidean algorithm in coconut

contents/cooley_tukey/code/rust/fft.rs, contents/cooley_tukey/cooley_tukey.md
@Liikt (and maybe @strega-nil) I felt like I had to do something ~~dirty~~ a little bit inelegant in order to make [Clippy](https://github.com/rust-lang/rust-clippy) shut up. (You'll see what I mean.)
=> Add FFT in Rust

.travis.yml, tools/deploy/update_site_travis.bash
The build in https://travis-ci.org/github/algorithm-archivists/algorithm-archive/builds/706151796 from https://github.com/algorithm-archivists/algorithm-archive/pull/720 exploded because the build directory changed from `build` to `_book` and I failed to review the code that wasn't changed. See https://github.com/algorithm-archivists/algorithm-archivists.github.io/tree/b27e0192c076a74f7a53915ae9233545061a6cb5 for effect.
=> Update Travis for HonKit build

contents/tree_traversal/code/coconut/tree_traversal.coco, contents/tree_traversal/tree_traversal.md
So there is the tree traversal chapter implemented in Coconut.
It should have everything, and if I missed anything, tell me.
=> Added tree traversal in Coconut

contents/computus/code/clisp/gauss-easter.lisp, contents/computus/computus.md
I'm very proud of this one. I took some time to clean it up right away and I'm happy with the result.
=> Computus Common Lisp Implementation

contents/euclidean_algorithm/code/python/euclidean_example.py, contents/euclidean_algorithm/euclidean_algorithm.md
=> Fixed infinite loop issue in "euclidean_example.py"

contents/huffman_encoding/code/python/huffman.py
=> fix both error of issue 739

contents/bogo_sort/bogo_sort.md, contents/bogo_sort/code/coconut/bogo.coco
Well, it's not really interesting, but I used more idiomatic Python for the `is_sorted` function, iterating over the array and a shifted copy of the array, rather than over the indices.
That's basically all I did from the Python implementation, except removing the `main` function, that serves little purpose in Python.
=> Added Bogosort in Coconut

contents/bubble_sort/bubble_sort.md, contents/bubble_sort/code/coconut/bubblesort.coco
Same as for Bogosort, I just slightly improved the Python code and removed the `main` function.
I opened those two PRs mainly to have them in Coconut, after thinking a bit about it. 
(Also, I forgot to click the button, so that's why this one arrived late compared to the Bogosort one; I implemented them the same day)
=> Added Bubblesort in Coconut

contents/euclidean_algorithm/code/nim/euclid_algorithm.nim
- `func` signifies that the procedures have no side effects: they are proper functions.
- Use the implicit `result` return variable instead of explicit returns.
- `when isMainModule` behaves the same way as `if __name__ == "__main__"` in Python.
=> Make Euclid's algorithm in Nim more idiomatic

contents/verlet_integration/code/nim/verlet.nim
- `func` signifies that the procedures have no side effects: they are proper functions.
- Prefer implicit return of the last expression over explicit return.
- `when isMainModule` behaves the same way as `if __name__ == "__main__"` in Python.
=> Make Verlet integration in Nim more idiomatic

contents/bogo_sort/code/nim/bogo_sort.nim
- `func` signifies that the procedures have no side effects: they are proper functions.
- Fix indentation to be 2 spaces instead of 4.
- Use the implicit `result` return variable instead of explicit returns.
- `when isMainModule` behaves the same way as `if __name__ == "__main__"` in Python.
=> Make Bogosort in Nim more idiomatic

CONTRIBUTORS.md, contents/cooley_tukey/code/clisp/fft.lisp, contents/cooley_tukey/cooley_tukey.md
Essentially a port of my Scala PR (#746) which appears to be stuck in review.
=> Added Cooley-Tukey in Common Lisp

contents/affine_transformations/affine_transformations.md
Fixed the github link at the end of the affine transformations chapter
=> Fix github profile link in the affine transformations chapter

book.json
This means that each website will say "Arcane Algorithm Archive" instead of "Honkit"
Apparently it takes me a while to actually RT(F)M
=> changing title of Algorithm Archive.

contents/IFS/code/c/IFS.c, contents/IFS/code/julia/IFS.jl
There were some inconsistencies in the naming scheme of the output files.
Now all implementations output into `sierpinski.dat` instead of `out.dat`.
=> Fix typos in IFS/julia and IFS/c

.github/workflows/build.yml, .github/workflows/deploy.yml, CONTRIBUTORS.md
Hello, this will require minor configuration in the repo settings.
Please read the full text, and references below before merging.
1. Merge the PR
1. You will need to go to `Settings` -> `Pages` -> `Source` -> `Branch`: Select `gh-pages`, `Folder`: Select `/(root)`
1. Hit `Save`
1.  This will deploy a version to [algorithm-archivists.github.io/algorithm-archive](algorithm-archivists.github.io/algorithm-archive)
1. If you do not see it here, wait 3-8 minutes.
Up to here, this is non destructive to the current deployment mechanisms.
<strong>You can stop here with no side effects to any services. I highly recommend taking a break here and letting github dns propagate</strong>
<b>The next change will bring down the site if it is incorrect.</b>
> Note: if you are hosting anything else on this …
=> Add support for github action workflows

contents/IFS/IFS.md, contents/IFS/code/java/IFS.java
This implementation uses a self created Point-Wrapper class.
It would be possible to use [Point2D.Double](https://docs.oracle.com/javase/8/docs/api/java/awt/geom/Point2D.Double.html), however this would hinder the readability of the code.
It is needed to clone the current point (line: 29), because if this is not done every entry of the array will reference the last point.
`main` throws an Exception due to the `FileWriter` creation, but a try-catch could also be used (at the cost of readability).
=> Add java implementation for Iterated Function Systems

.github/workflows/build.yml
UI naming fix. Doesn't affect anything but the name that's reported in the PR
=> rename task to just build from build and deploy from GH actions

contents/euclidean_algorithm/euclidean_algorithm.md
Kotlin was missing for the list of languages for the Euclidean algorithm
=> adding kotlin back to the chapter for the euclidean algorithm

contents/tree_traversal/code/julia/Tree.jl
This fixes #841 by using the recommend functions instead.
=> Tree traversal: Change front and top to first

book.json, contents/stacks_and_queues/stacks_and_queues.md
=> adding stack and queue code infrastructure

contents/barnsley/barnsley.md, contents/barnsley/code/c++/barnsley.cpp
The Barnsley Fern with 100000 points
=> C++ sample code for The Barnsley Fern

contents/approximate_counting/code/julia/approximate_counting.jl
This was brought up in the discussion of #834 
Feel free to make other comments about the code on this PR!
=> small typos in julia code that could be a problem in other languages. Added abs and fixed <=

contents/jarvis_march/code/csharp/Program.cs
This uses the points from https://github.com/algorithm-archivists/algorithm-archive/blob/4313e7eb3d2faa152590c631d180d06a5c85f46d/contents/graham_scan/code/julia/graham.jl#L50
=> Update C# Jarvis March to use points from Graham Scan

contents/IFS/IFS.md, contents/IFS/code/haskell/IFS.hs
I could not resist generalizing the algorithm a little bit, in my version Hutchinson Operators are an argument of the function. 
I used [Ormolu](https://github.com/tweag/ormolu) as the code formatter for the first time. I like formatter without config files so I'll probably keep using that.
=> [Haskell] IFS

contents/verlet_integration/code/asm-x64/verlet.s, contents/verlet_integration/code/c++/verlet.cpp, contents/verlet_integration/code/c/verlet.c, contents/verlet_integration/code/clisp/verlet.lisp, contents/verlet_integration/code/fortran/verlet.f90, contents/verlet_integration/code/golang/verlet.go, contents/verlet_integration/code/haskell/verlet.hs, contents/verlet_integration/code/java/Verlet.java, contents/verlet_integration/code/javascript/verlet.js, contents/verlet_integration/code/julia/verlet.jl, contents/verlet_integration/code/kotlin/verlet.kt, contents/verlet_integration/code/nim/verlet.nim, contents/verlet_integration/code/python/verlet.py, contents/verlet_integration/code/ruby/verlet.rb, contents/verlet_integration/code/rust/verlet.rs, contents/verlet_integration/code/swift/verlet.swift
This PR tries to standardize the different kinds of outputs to use the ones outlined in #824.
The following implementations are not [yet] standardized:
- ~~asm-x64~~ (done thanks to @leios)
- ~~haskell~~ (done thanks to @jiegillet)
- labview (does not have text output)
- matlab (does not have text output)
- scratch (does not have text output)
As I am not comfortable enough changing the asm/haskell code, someone else should take a look at these implementations.
I can confirm that every (standardized) implementation now produces the same [numerical] results as the julia one and that no `md` files need to be modified here.
Please review this carefully, as this kind of output standardization needs to be done for every chapter and this PR sets the ground rules for future optimizations.
=> Verlet Integration: Output standardization

contents/monte_carlo_integration/code/asm-x64/monte_carlo.s, contents/verlet_integration/code/asm-x64/verlet.s
This PR fixes the asm implementations which previously did not return 0 as an exit code.
The affected implementations are the following:
- Verlet Integration
- Monte Carlo Method
This was already done in some others, but this aims to standardize it across different implementations.
=> Fix asm exit codes

contents/flood_fill/code/coconut/flood_fill.coco, contents/flood_fill/flood_fill.md
This replaces #743, because I merged the master branch, and thought it could have been a good idea.
Anyway, here's the good one, normally. It should have the code in the same state as the last commit from the previous PR.
I'm probably going to delete the old branch in a few days (if I remember it then)
=> Flood fill in Coconut

.devcontainer/Dockerfile
Part of #871.
I've documented this in the Dockerfile but you can run scripts with `vim -c ":source %" <path_to_file>`.
=> Add devcontainer setup for VimL/Vim script

SConstruct
This fixes SCons on Windows when MSVC is installed.  Previously it would attempt to use MSVC, but fail due to trying to pass it gcc libraries to link.
This needs testing on Linux before it is merged.
It may be better to have the sconstruct file detect which compiler is being used and adjust the calling based on that, so users with only MSVC or with clang can also build. Fixing it for now would still seem prudent, and we can change the behaviour later if wanted.
=> Force SCons to use GCC when building .c files

SConstruct, contents/cooley_tukey/code/asm-x64/SConscript, contents/forward_euler_method/code/asm-x64/SConscript, sconscripts/asm-x64_SConscript
And here we go again with X64 Assembly.
There was a little annoyance this time: the way we programmed the assembly required the compilation to use the link flag `-no-pie`. As such, to prevent environment duplication, I elected to add the link flag to all the executables.
Apart from this, compilation was not affected, and all executables compile successfully on my Linux machine.
We really should set up a Windows environment to check whether it works as intended there, though.
=> Added x64 assembly compilation

SConstruct, sconscripts/go_SConscript
Adds Go to SCons.
Probably should be checked on docker, but it's probably too simple to fail.
=> Add Go to SCons

SConstruct, contents/euclidean_algorithm/code/fortran/SConscript, sconscripts/fortran_SConscript
And here we go with the next language: Fortran.
Adding it was straightforward since there was no library to add.
The only problem was the double definition of the `build/fortran/euclidean_algorithm` target, which I had to create a SConscript for.﻿
=> Added Fortran compilation

SConstruct
This is a PR to remove the expectations of no warning for C++﻿, to allow for some time to fix the C++ warnings properly.
Before running SCons in a pipeline, we need to remove the warnings in C++, as they would give wrong results.
=> Removed C/C++ warnings only for C++

.github/workflows/publish_container.yml
This prevents this action from failing in forked repositories
=> Change the "Publish Container" Action to only run in the main repository

contents/IFS/code/c/IFS.c, contents/IFS/code/clisp/ifs.lisp, contents/IFS/code/haskell/IFS.hs
This PR aims to standardize the output file name and the amount of points generated.
The output file will now always be named `sierpinski.dat` and it will contain 10000 points.
=> IFS: Standardize output files

sconscripts/coconut_SConscript
The issue this PR fixes is the following:
When building for the first time, the Coconut compiler considers the build target a directory.
However, when running a second time, SCons is confused because it expected a file.
This can be fixed by adding the `.py` suffix to the build target (see the Coconut SConscript).
﻿
=> Fixed Coconut compilation problem

contents/tree_traversal/code/python/tree_traversal.py, contents/tree_traversal/tree_traversal.md
Made it more pythonic and compact. Usage of temp variable wasn't necessary nor was the loop through children or the appending of the root node to the stack.
=> Updated tree traversal chapter

contents/forward_euler_method/code/coconut/euler.coco, contents/forward_euler_method/forward_euler_method.md
Okay, so the commits show two possible versions of the Forward Euler method in Coconut.
Before editing the md file, I want to have some feedback on that.
I'm not sure I can have something more functional style than that, but it could be.
If there's no way, which version do you prefer? V1 is more concise and efficient for checking, but might be more confusing to beginners. V2 could maybe be made a little bit more functional style, and doesn't need creating a list or an array.
=> Forward Euler method in Coconut

contents/IFS/IFS.md, contents/stacks_and_queues/stacks_and_queues.md
I opened this PR to solve some critical formatting problems, that were incompatible with AAA-py rendering.
Rendering with AAA-py is blocked until this PR is merged, although Honkit works correctly with it (at least failure is not fatal).
However, the Java `Stack and Queues` chapter code inclusion is broken in all cases, and this fixes that problem.
=> Solved formatting problems

SConstruct, builders/kotlin.py, sconscripts/kotlin_SConscript
This PR is to add Kotlin compilation to SCons.
I have decided to compile to a JAR because compiling to individual classes was more anoying.
I could probably compile to a JAR including the Kotlin runtime, but this did not seem necessary.
The tool is taken nearly directly from the scons-contrib repository (under MIT license).
If you have any other remarks, feel free to put them below.﻿
=> Added Kotlin compilation

SConstruct, contents/IFS/code/c/IFS.c, contents/approximate_counting/code/c/approximate_counting.c, contents/cooley_tukey/code/c/fft.c, contents/cooley_tukey/code/cpp/fft.cpp, contents/forward_euler_method/code/c/euler.c, contents/forward_euler_method/code/cpp/euler.cpp, contents/gaussian_elimination/code/cpp/gaussian_elimination.cpp, contents/graham_scan/code/c/graham.c, contents/huffman_encoding/code/c/huffman.c, contents/monte_carlo_integration/code/c/monte_carlo.c, contents/split-operator_method/code/c/split_op.c, contents/split-operator_method/code/cpp/split_op.cpp, contents/stable_marriage_problem/code/c/stable_marriage.c, contents/thomas_algorithm/code/c/thomas.c
This PR is to remove all implicit conversions in both the C and C++ codes we have.
Each file change was put in its own commit for easier revertability.
Most changes were mainly following the compiler instructions, athough a few codes needed a change of types in their structure (looking at Huffman encoding in C).
I can confirm each code compiles correctly on my machine, *with* the Conversion error in place.
If you have trouble with compilation on Windows because of the change, please put it below and we'll see what we can do.
There should not be a problem on Linux, though.
=> Eliminating C/C++ implicit conversions

contents/huffman_encoding/code/ocaml/huffman.ml
References -> https://ocaml.org/learn/tutorials/99problems.html
=> Implement huffman encoding in ocaml

SUMMARY.md
Due to a trailing space in the summary, the AAA-py implementation had an erroneous link to the Probability distribution chapter.
This and [AAA-py PR#24](https://github.com/algorithm-archivists/aaa-py/pull/24) solve the problem from both sides.
=> Use stricter formatting

contents/verlet_integration/verlet_integration.md
This fixes #994 and explains why the error term is actually dt^2 for Stormer Verlet
=> adding more info on stormer verle

.gitignore, SConstruct, builders/racket.py, sconscripts/racket_SConscript
This is a PR to add Racket to the build system.
This has been tested on my Linux (Ubuntu 22.04) machine, and works correctly on the two Racket examples we have in the AAA.
=> Adding Racket to the build system

Dockerfile, SConstruct, builders/mcs.py, contents/huffman_encoding/code/csharp/HuffmanCoding.cs, contents/tree_traversal/code/csharp/Tree.cs, sconscripts/csharp_SConscript
This is a PR to add C# to our build system, making sure we have a common ground.
I see we have the dotnet sdk, but I could not find the command to compile using it, don't hesitate to close this PR if you give me the proper way.
Because I used Mono, there were a few changes in two files, as Mono doesn't allow functions inside functions, apparently.
This follows from #1011, but might need to be merged before.
=> Adding C# to the build system (using the Mono toolchain)
