chapters/computational_physics/verlet.md

Added Python example for Verlet

Added Python example for Verlet

---

README.md

Add link to the Arcane-Algorithm-Archive-gitbook-page in README.md for easy accessibility.

Add link to gitbook-page in README

---

chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md

If the changes are that little, I think negative number support isn't that messy as I thought.

Add negative number support for EuclideanAlg C#

---

chapters/fundamental_algorithms/tree_traversal/tree_traversal.md

I didn't update the C++ in the body, because I think it should be changed to pseudocode

update C++ to newstyle

---

chapters/mathematical_background/taylor_series.md

What you did James, didn't make sense or would lead people astray.

Fixing an error

---

chapters/computational_mathematics/FFT/fft.hs

https://scratch.mit.edu/projects/37759604/

Added Cooley-Tukey in Haskell. Bit reverse version on Scratch:

---

book.json
chapters/computational_mathematics/FFT/cooley_tukey.md
chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md
chapters/fundamental_algorithms/sorting_searching/bogo/bogo_sort.md
chapters/fundamental_algorithms/tree_traversal/tree_traversal.md

Update book.json and mult-lang implementation where needed.

Enhance mult-lang.

---

chapters/fundamental_algorithms/euclidean_algorithm/code/clojure/euclidean_example.clj
chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md

not much but it's a start :)
sorry I didn't know how to preview the the book so expect things to break

add clojure to euclidean algorithm in fundamental algorithms

---

book.json

Regarding this issue https://github.com/leios/algorithm-archive/issues/41

Disable split-view as default.

---

chapters/computational_mathematics/decision_problems/stable_marriage/code/python/stable_marriage.py
chapters/computational_mathematics/decision_problems/stable_marriage/stable_marriage.md

If merged, this Pull Request will add an object oriented Python 3 version of the Gale-Shapley algorithm.

Added Python code for the stable marriages chapter

---

chapters/computational_mathematics/FFT/code/c++/fft.cpp

I made some minor stylistic updates to the C++ implementation of FFT, and I think it turns out a bit more readable. Also, some of the comments were updated.

Some minor updates to the C++ FFT

---

chapters/computational_mathematics/decision_problems/stable_marriage/code/c++/stable_marriage.cpp

The C++ code for Gale-Shapley algorithm wasn't very clear so I made it have it's own function.

making the algorithm more clear

---

chapters/fundamental_algorithms/euclidean_algorithm/code/c++/euclidean.cpp
chapters/fundamental_algorithms/euclidean_algorithm/euclidean.md

Incredibly minor change, but I'm just looking over all the C++ files due to #60

slight restyling of euclidean.cpp

---

book.json
chapters/computational_physics/euler/code/elm/elm-package.json
chapters/computational_physics/euler/code/elm/euler.elm
chapters/computational_physics/euler/elm_app_full_code.md
chapters/computational_physics/euler/euler.md

This pull request is a cleand up version of #62. I got the branch up-to-date with master and removed the already merged commits/merge commits. I also changed a bit that we (I think) collectively agreed on, which is that the HTML file is code output and should, for that and other reasons, not be included.
I preserved the original commit author, so that @jiegillet still shows up as the contributor of the code.

Cleaned up "Added Elm code for Euler, with visualization" (#62)

---

chapters/sorting_searching/bubble/bubble_sort.md
chapters/sorting_searching/bubble/code/haskell/bubbleSort.hs

Added bubble sort.
Funnily enough, bogo sort is considerably harder in Haskell, I'm working on it :)

Bubble Sort in Haskell

---

chapters/computational_geometry/gift_wrapping/jarvis_march/code/haskell/jarvisMarch.hs

Only the code, I didn't include it in the .md file.

Jarvis March in Haskell

---

CONTRIBUTORS.md
chapters/computational_geometry/gift_wrapping/gift_wrapping.md
chapters/data_compression/huffman/code/c++/huffman.cpp
chapters/data_compression/huffman/code/clojure/huffman.clj
chapters/data_compression/huffman/huffman.md
chapters/euclidean_algorithm/code/clojure/euclidean_example.clj
chapters/euclidean_algorithm/euclidean.md
chapters/sorting_searching/bogo/bogo_sort.md
chapters/sorting_searching/bogo/code/clojure/bogo.clj

Hello guys,
sorry for not contributing for a long time.  could someone tell me how
to see the book from my computer to check if everything is good,
thanks

Implement huffman algorithm in clojure

---

.editorconfig

I don't know how I managed to forget Java, but here it is. I set it to 4 spaces for indentation for all .java files.

Added .java files to .editorconfig

---

book.json
chapters/sorting_searching/bubble/bubble_sort.md
chapters/sorting_searching/bubble/code/d/bubble_sort.d

This will add an example implementation of bubble sorting in d, based on the C++ implementation.

Add d language example to bubble sort

---

.editorconfig

I just merged #139 and thought it would be a good idea to include D in .editorconfig.

Added EditorConfig rules for .d files

---

chapters/sorting_searching/bubble/bubble_sort.md

I prematurely merged #139 and didn't pay attention to the fact that none of the other code examples show the main function, so I limited the import range to the actual bubbeSort function.

Added a line range to  the Bubble Sort D code import

---

chapters/monte_carlo/code/clojure/monte_carlo.clj
chapters/monte_carlo/monte_carlo.md

sorry for the other PR, but it works now

add monte carlo in clojure

---

.editorconfig
chapters/differential_equations/euler/code/elm/elm-package.json

Now that book.json uses 2 space indentation, I added that rule to .editorconfig, like always.
There was also one other JSON file, which I also converted while I was at it.

Added JSON to .editorconfig and converted all JSON files

---

chapters/euclidean_algorithm/euclidean.md

A line of code in euclidean.md for Go was missing so I added it in

Adding a missing line of code in euclidean.md

---

chapters/euclidean_algorithm/code/swift/euclidean_algorithm.swift
chapters/euclidean_algorithm/euclidean.md

- Adding Euclidean Algorithm in Swift
- Updating .md

Adding Euclidean Algorithm in Swift

---

chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md

This PR fixes a markdown file with an error that breaks the build of the entire book. The error was introduced in #273.

Fixed the broken build

---

contents/monte_carlo_integration/code/swift/monte_carlo.swift

- Edited Percent Error Calculation to comply with #324

Updating Monte Carlo in Swift

---

book.json

See [this PR](https://github.com/algorithm-archivists/gitbook-plugin-api-language-selector/pull/1) for more info/changes

Changed referecne of api-language-plugin to archive-archivist version

---

styles/website.css

Fix website.css

---

contents/bogo_sort/bogo_sort.md
contents/bubble_sort/bubble_sort.md
contents/euclidean_algorithm/euclidean_algorithm.md
contents/huffman_encoding/huffman_encoding.md
contents/jarvis_march/jarvis_march.md
contents/monte_carlo_integration/monte_carlo_integration.md
contents/stable_marriage_problem/stable_marriage_problem.md
contents/tree_traversal/tree_traversal.md

Some programs use multiple files and have the title of the file above the code. Currently there is no formatting on these titles.
I added in '#####' before these titles which I think looks a little nicer.
This might just be a personal preference though so I understand if it isn't merged.

Adding Formatting to File Names

---

CONTRIBUTORS.md
book.json
contents/euclidean_algorithm/code/nim/euclid_algorithm.nim
contents/euclidean_algorithm/euclidean_algorithm.md

implemented the euclid algorithm in Nim and added nim to book.json

implemented euclid algorithm in nim

---

contents/euclidean_algorithm/euclidean_algorithm.md

I recognised that the code examples in the page markdown were in an odd order.

Euclidean julia edit

---

contents/monte_carlo_integration/code/java/MonteCarlo.java

- Edited Percent Error Calculation to comply with #324

Updating Monte Carlo in Java

---

contents/monte_carlo_integration/code/javascript/monte_carlo.js

Edited Percent Error Calculation to comply with #324

Updating Error Calculation for Monte Carlo in Javascript

---

contents/monte_carlo_integration/code/c/monte_carlo.c

Fixing percentage error in monte_carlo.c

---

contents/euclidean_algorithm/code/c++/euclidean.cpp
contents/euclidean_algorithm/euclidean_algorithm.md
contents/tree_traversal/code/c++/tree_example.cpp
contents/tree_traversal/tree_traversal.md

After I talked to ubsan and told her about the C++ style decisions, she requested me to remove her name from the C++ files, that contain her name.
So this PR does exactly that.
It also removes the credit in general, if you (@leios ) don't want that, feel free to tell me, then I re-add it again.

Remove credit for ubsan (and in general) from two C++ files.

---

contents/cooley_tukey/code/julia/fft.jl
contents/cooley_tukey/cooley_tukey.md
contents/gaussian_elimination/code/julia/gaussian_elimination.jl
contents/gaussian_elimination/gaussian_elimination.md
contents/graham_scan/code/julia/graham.jl
contents/split-operator_method/code/julia/split_op.jl
contents/split-operator_method/split-operator_method.md
contents/stable_marriage_problem/code/julia/stable_marriage.jl
contents/tree_traversal/code/julia/Tree.jl

This is a quick update to all the julia code so that it runs in Julia V1.0

Update all julia code to V1.0

---

contents/cooley_tukey/code/clojure/fft.clj
contents/cooley_tukey/cooley_tukey.md

I'm really sorry for being this late,
I made a main function and removed the unnecessary library for matrix multipication

implement fft in clojure

---

contents/thomas_algorithm/code/swift/thomas.swift
contents/thomas_algorithm/thomas_algorithm.md

Added Thomas Algorithm in Swift

Adding Thomas Algorithm in Swift

---

.travis.yml

Does this fix the travis stuff?

adding smallscale fix to .travis.yml file.

---

CONTRIBUTING.md
CONTRIBUTORS.md
LICENSE.md

- Use a normal list in CONTRIBUTING, rather than HTML
- Update license copyright year
- Unfill text that doesn't change presentation

Markdown formatting updates

---

.gitignore

Add some texteditors to the gitignore

---

contents/bubble_sort/bubble_sort.md
contents/bubble_sort/code/kotlin/BubbleSort.kt

This commit adds a simple implementation of Bubble Sort in Kotlin. It is
very similar to the Java implementation.
Example output:
```
❯ kotlinc BubbleSort.kt && kotlin BubbleSortKt
Original [4, 2, 9, 20, 11, 30, 1, 0]
Sorted   [0, 1, 2, 4, 9, 11, 20, 30]
```

Add Bubble Sort implementation in Kotlin

---

.editorconfig
contents/bogo_sort/code/lua/bogosort.lua
contents/bubble_sort/code/lua/bubble_sort.lua
contents/monte_carlo_integration/code/lua/monte_carlo.lua
contents/monte_carlo_integration/monte_carlo_integration.md

Another short PR, spent enough time reviewing C and PHP implementations so decided I'd write the lua version. Doesn't provide variable radius since it's not really necessary for calculating pi.

Monte Carlo in Lua

---

contents/quantum_systems/code/c/energy.c
contents/quantum_systems/quantum_systems.md

This pull request is meant to fix the C file by fixing a case problem and including the C standard library that implements booleans (`stdbool.h`).

C quantum system fixes

---

contents/forward_euler_method/code/golang/euler.go
contents/forward_euler_method/forward_euler_method.md

run with go version `go1.11 linux/amd64`

add the forward euler method in golang

---

contents/bubble_sort/bubble_sort.md
contents/euclidean_algorithm/euclidean_algorithm.md
contents/monte_carlo_integration/monte_carlo_integration.md
contents/tree_traversal/tree_traversal.md

change the name "golang" to "go"

change the name golang to go

---

tools/cleanup/clean_book_json.py
tools/cleanup/clean_editorconfig.py

Two quick scripts, as discussed in #499 
Please test and review :)

Cleanup files

---

contents/bogo_sort/bogo_sort.md
contents/bogo_sort/code/r/bogo_sort.r

This is my first try in R. I hope it's ok :sweat_smile:

Add Bogo sort in R

---

contents/huffman_encoding/code/lua/huffman.lua
contents/huffman_encoding/huffman_encoding.md

Everything should be here. Accidently submitted a PR to my forks master *derp*.

Added Huffman for Lua

---

contents/monte_carlo_integration/code/bash/monte_carlo.bash
contents/monte_carlo_integration/monte_carlo_integration.md

Code would need more echo ""|bc or dc if I used radius of 1 so used radius of 32767(limit of random), should be ok?

Added monte carlo in bash

---

book.json
contents/bogo_sort/bogo_sort.md
contents/bubble_sort/bubble_sort.md
contents/convolutions/convolutions.md
contents/cooley_tukey/cooley_tukey.md
contents/forward_euler_method/forward_euler_method.md
contents/gaussian_elimination/gaussian_elimination.md
contents/graham_scan/graham_scan.md
contents/huffman_encoding/huffman_encoding.md
contents/jarvis_march/jarvis_march.md
contents/monte_carlo_integration/monte_carlo_integration.md
contents/quantum_systems/quantum_systems.md
contents/split-operator_method/split-operator_method.md
contents/stable_marriage_problem/stable_marriage_problem.md
contents/thomas_algorithm/thomas_algorithm.md
contents/tree_traversal/tree_traversal.md
contents/verlet_integration/verlet_integration.md

Add the prism syntax highlighting plugin to the AAA, set its config and modify some import statements.
The plugin on GitBook Plugins: https://plugins.gitbook.com/plugin/prism
Solves #96

Add the Prism Syntax Highlighting Plugin

---

SUMMARY.md

Hey guys,
I have been revising most of the chapters as of late. This chapter in particular needs heavy re-work and will not look remotely similar to what it did before. Unlike other revisions, almost all the code for this chapter will need to be re-written, so it makes sense to remove it during the revision instead of leaving it up. For the time-being, I would like to just remove it from the `SUMMARY.md`.
Sorry for the inconvenience!

removing convolutions chapter while reworking it

---

contents/bogo_sort/code/python/bogo.py

There was a little typo in the bogo sort python implementation.

tiny fix to bogo sort in python

---

contents/tree_traversal/tree_traversal.md

adding l to ideal in tree traversal

---

contents/gaussian_elimination/gaussian_elimination.md

fixing typo in step 2 of Gaussian Elimination

---

contents/euclidean_algorithm/euclidean_algorithm.md
contents/graham_scan/code/julia/graham.jl

A small mistake I noticed when looking through the Graham Scan chapter. Here's a quick fix.

Minor correction

---

CONTRIBUTORS.md
contents/tree_traversal/code/c++/tree_example.cpp

- node has no member `children_size`, using `children.size()`;
- `create_node` is wrong, using `create_tree`

Fix tree traversal C++ code

---

.editorconfig
book.json
contents/forward_euler_method/code/v/euler.v
contents/forward_euler_method/forward_euler_method.md

V forward euler

---

.travis.yml

Changing node version in travis script with the hopes of fixing the build error

---

contents/computus/code/crystal/gauss_easter.cr
contents/computus/computus.md

Based on the julia implementation.

Implemented Computus in Crystal

---

contents/bogo_sort/bogo_sort.md
contents/bogo_sort/code/lua/bogosort.lua
contents/bubble_sort/code/lua/bubble_sort.lua
contents/euclidean_algorithm/code/lua/euclidean.lua
contents/huffman_encoding/code/lua/huffman.lua
contents/monte_carlo_integration/code/lua/monte_carlo.lua
contents/monte_carlo_integration/monte_carlo_integration.md
contents/thomas_algorithm/code/lua/thomas.lua

* Proper use of `local`
* Proper use of snake_case
* Removed a bunch of dead spaces
* Fixed monte carlo code to be equivalent to other implementations
* Added comment from the julia implementation to monte carlo code.

Unified Lua code style across pages

---

contents/thomas_algorithm/code/javascript/thomas.js
contents/thomas_algorithm/thomas_algorithm.md

This is an update to #491, this fork was abandoned, but that PR was adequately reviewed, so I am happy to merge this unless we would prefer #647.
I will give everyone a few days to decide. Obviously, I am not a javascript guy, so this was just fixing up the preview *reviewed* pr for javascript.
Unfortunately, because the fork was deleted, I could not quite get the history, so I co-authored @Yordrar

Thomas alg in Javascript fixup

---

contents/gaussian_elimination/gaussian_elimination.md

As it says, I am just fixing the line numbers so the reflect the code. They are missing in the current chapter.

fixing line numbers for codeblocks with go and Gaussian Elimination

---

contents/IFS/IFS.md

I screwed up and imported the wrong line numbers in the second julia text box for IFS

fixing line numbers in IFS chapter

---

contents/jarvis_march/code/c/jarvis_march.c

This uses the points from https://github.com/algorithm-archivists/algorithm-archive/blob/4313e7eb3d2faa152590c631d180d06a5c85f46d/contents/graham_scan/code/julia/graham.jl#L50

Update C Jarvis March to use points from Graham Scan

---

CONTRIBUTORS.md
styles/website.css

For issue #711. I closed the old one of this & updated it, this fixes the type to search input as well.

Update search q css

---

contents/graham_scan/code/coconut/graham_scan.coco
contents/graham_scan/graham_scan.md

And there is the new Coconut implementation for the Graham scan.
I basically copied the Python implementation and sparkled a few purely Coconut feature, but that's all.
I tested it, and it outputs the same thing as the Python one.

Added Graham scan in Coconut

---

contents/monte_carlo_integration/code/coconut/monte_carlo.coco
contents/monte_carlo_integration/monte_carlo_integration.md

As said on Discord, there is the Monte Carlo Integration implementation in Coconut today.
As always, if there's any error or any formatting problem, tell me.

Added Monte Carlo integration in Coconut

---

styles/website.css

Adding some CSS rules to enable printing of pages without the side bar getting in the way and without the content stopping after the first page.
The problems with printing/print preview where mentioned in #665.

Added CSS for printing pages

---

contents/approximate_counting/code/julia/approximate_counting.jl

fixing order of function arguments

---

contents/convolutions/code/julia/1d_convolution.jl
contents/jarvis_march/code/csharp/Program.cs

Fixes #852. Fixes #852. 
Hopefully, since I'm not a Julia master :)

[#852] [#852] Fix for Julia 1D convolution

---

.github/workflows/build.yml

This is a PR to use parallel compilation ﻿during the build action.
This will hopefully make the compilation go faster (not that we curently need it, but it's still a nice addition for the future).

Tweaked SCons compilation action step

---

contents/IFS/IFS.md
contents/affine_transformations/affine_transformations.md
contents/approximate_counting/approximate_counting.md
contents/barnsley/barnsley.md
contents/bitlogic/bitlogic.md
contents/computus/computus.md
contents/domain_coloring/domain_coloring.md
contents/euclidean_algorithm/euclidean_algorithm.md
contents/flood_fill/flood_fill.md
contents/forward_euler_method/forward_euler_method.md
contents/gaussian_elimination/gaussian_elimination.md
contents/huffman_encoding/huffman_encoding.md
contents/monte_carlo_integration/monte_carlo_integration.md
contents/split-operator_method/split-operator_method.md
contents/stable_marriage_problem/stable_marriage_problem.md
contents/tree_traversal/tree_traversal.md
contents/verlet_integration/verlet_integration.md

I don't know how exactly, but every time we load a youtube video, it will load fonts.gstatic.com.
There was a German court that says German sites owe 100 Euro to those using google fonts. I am not sure if this counts, but if it does, I can just remove the youtube embeds. They don't really serve a practical purpose for the website, itself.
Link: https://news.ycombinator.com/item?id=30135264

Small changes to youtube embeds to prevent google spying on everyone

---

Dockerfile

Because pushing both the Dockerfile changes and the SCons changes didn't work, here is the C# Docker change

Add C# compilation with Mono
